services:
  - type: web
    name: postgresql-project-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_dIv8BE3xbztX@ep-proud-king-ayssnkrq.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: bd103d3aa73046abb2a58c1eabb6222a2a5224a574af4ebbbe3c071d0de0d8e5
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 10
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: wasm
